### ISSUE TITLE
Current issues

### ISSUE THREAD

**Issue by NickKury** [jjiiaaLi/QuoraHistoryCloneProject#19]
1. When trying to edit/delete someone else's question
     - possible fix, hide buttons from other users

2. Clicking on the search button gives a 404
     - possible fix, remove button

3.  Clicking on the a questions tag give a 404
     - was the functionality suppose to redirect to a page of questions associated with the tag?

4. When submitting a new question <tagIds.forEach is not a function>
     - the question is posted when returning to the home page but with no tag

5.  Cant look at a question/answer page unless logged in

**Comment by jjiiaaLi** [comment]
Addressing topic #2
search button has since been removed and changed to view user profile link which takes them to a page that renders a display of their username and emailaddress as well as an option to edit their profile or simply return to home page

**Comment by jjiiaaLi** [comment]
in home page above each question and below username for each question, the tag clicks into an error
